on: push

jobs:
  build-and-deploy:
    name: Running tests
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: 'Install dependencies'
        run: |
          npm install
      - name: Run tests
        run: |
          npm run test
      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v1
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}